### ISSUE TITLE
curl

### ISSUE THREAD

**Issue by john96dk** [Impact123/CallAdmin#21]
hey i have a problem with calladmin client when i do update trackers i get a messge from windown saying couldn't init curl connect any way to fix it

**Comment by Impact123** [comment]
[The client has its own issue tracker](https://github.com/popoklopsi/CallAdmin-Client), but this is not an issue that can be fixes just yet because you haven't posted enough information. Please post this in [the forum thread](https://forums.alliedmods.net/showthread.php?t=213670) after reading [the getting help article](https://github.com/Impact123/CallAdmin/wiki/Getting-Help).
