### ISSUE TITLE
[Feature Request] Add Cvar for Custom IP/Domain Names for Reports from the server

### ISSUE THREAD

**Issue by TandelK** [Impact123/CallAdmin#28]
In most of the scenario i see that plugin automatically finds the IP and sent to Reported Module like Steam or Custom like Discord. The issue which most of server operator face is ip is set to 0.0.0.0 and even with changing in server.cfg about hostip as the real IP still we get same IP all over the place. 

Can you make a cvar that which IP to be reported like we can add own Custom Domains for Reports. That will make the work more easier.

**Comment by Impact123** [comment]
There was a bug in earlier versions where the hostip conversion didn't work that well. [This was fixed in version **0.1.6**](https://github.com/Impact123/CallAdmin/wiki/Changelog#016) though and using a conversion tool like [this](https://www.smartconversion.com/unit_conversion/IP_Address_Converter.aspx) should work just fine.
For example you have the external ip `74.125.206.94` you convert it and it becomes `1249758814`
Adding `hostip "1249758814"` to the end of your server.cfg should do the trick.
I prefer to fix the ip detection before adding a new convar, i hope you understand.
You can [add me on steam](https://steamcommunity.com/profiles/76561198026608681/) if you want, I'm interested to find out why this bug occurs on your server(s).

**Comment by TandelK** [comment]
Closing the issue as it has been resolved using Convertor and Custom COmmands by @Impact123 himself , Thanks a lot
