### ISSUE TITLE
CallAdmin not sending messages and giving errors at start

### ISSUE THREAD

**Issue by friendzpt** [Impact123/CallAdmin#30]
This is the error:

L 12/01/2018 - 23:08:32: [SM] Exception reported: Could not open file "csgo/"
L 12/01/2018 - 23:08:32: [SM] Blaming: calladmin.smx
L 12/01/2018 - 23:08:32: [SM] Call stack trace:
L 12/01/2018 - 23:08:32: [SM]   [0] LogToFileEx
L 12/01/2018 - 23:08:32: [SM]   [1] Line 263, C:\Users\friendz-\Desktop\sourcemod-1.9.0-git6261-windows\addons\sourcemod\scripting\calladmin.sp::Native_LogMessage
L 12/01/2018 - 23:08:32: [SM]   [3] CallAdmin_LogMessage
L 12/01/2018 - 23:08:32: [SM]   [4] Line 129, C:\Users\friendz-\Desktop\sourcemod-1.9.0-git6261-windows\addons\sourcemod\scripting\calladmin_steam.sp::OnPluginStart
L 12/01/2018 - 23:08:32: [SM] Unable to load plugin "calladmin_steam.smx": Error detected in plugin startup (see error logs)

The plugin works, I can report and it opens the menu after !call and everything but there the bot dont send any message. The login information is correct

**Comment by Impact123** [comment]
I can see you compiled this yourself. Why? Did you modify anything? You can usually get information on load up errors via `sm plugins info calladmin_steam` from the server console as described on [the Getting Help page from the wiki](https://github.com/Impact123/CallAdmin/wiki/Getting-Help#plugin-info). By [looking at the line numbers](https://github.com/Impact123/CallAdmin/blob/0.1.8/gameserver/calladmin_steam.sp#L129) i can tell that this error occurs because you miss the latest version of [the MessageBot extension](https://github.com/dordnung/MessageBot). You can download it from [its releases page](https://github.com/dordnung/MessageBot/releases). I think i know why it tries to log to `csgo/`, I'll update this issue when it's fixed.

**Edit**: [This is now fixed](https://github.com/Impact123/CallAdmin/commit/fe60a5e23b5a47d45af531b54d9c3551e548c5e4), thanks for your report.

**Comment by friendzpt** [comment]
Yea, I updated the MessageBot extension and System2 and it works ;)
