### ISSUE TITLE
[TS3 Module] Cannot unset $this in ... /Server.php on line 2252

### ISSUE THREAD

**Issue by Bl4CkGuuN** [Impact123/CallAdmin#35]
Hey,

at http://domain.com/calladmin/ts3/userlist.php?key=mykey I get this error: 
`Fatal error:  Cannot unset $this in /www/htdocs/cs/calladmin/ts3/include/TeamSpeak3/Node/Server.php on line  2252`

It is connecting every 20 seconds to the Teamspeak (is this normal?)

Also in the database the ServerIP and Port is empty.

**Comment by Impact123** [comment]
Please open individual issues for multiple/unrelated issues.

## First issue
[The first issue was fixed in the development version by updating the Teamspeak library](https://github.com/Impact123/CallAdmin/commit/5806efa6a5156f1342f5c7bb1be286ff4ed5f24a), see [Changelog](https://github.com/Impact123/CallAdmin/wiki/Changelog#019-dev). You can download it from [the releases page](https://github.com/Impact123/CallAdmin/releases).

## Second issue
The second issue requires [additional information](https://github.com/Impact123/CallAdmin/wiki/Getting-Help). Please install [the latest development version](https://github.com/Impact123/CallAdmin/releases) and let me know if this fixes the issues. If not please come back (or [add me on steam](https://steamcommunity.com/profiles/76561198026608681/)) with the required information and we'll figure it out. The 20 second connection is normal, it's used for the tracker/admin count feature.

**Comment by Bl4CkGuuN** [comment]
So with the ts3 development version it's working now.
In the teamspeak message is the ip, so that works too. It just not in the database, but that doesnt matter.

Thanks for your help
